Using time_origin in scipy extrapolation error message
Running unit test in script now gives error
Error: U sampled outside time domain at time 2001-12-31 00:00:00. Try
setting allow_time_extrapolation to True

Which is much more informative than original error message