Adding a unit test where fieldset.add_vector_field() is called without the individual fields being added
This causes a `AttributeError: 'Field' object has no attribute 'ccode_name'`, as also reported in #937